// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Contract struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	StartDate   pgtype.Timestamp
	Active      bool
	Responsible pgtype.UUID
}

type ContractEvent struct {
	ID         uuid.UUID
	ContractID string
	Type       string
	Ts         pgtype.Timestamp
	Processed  bool
	Data       []byte
}

type Employee struct {
	ID   uuid.UUID
	Name string
}
